### ISSUE TITLE
Fiona error

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#1]
After first setup following the readme I run into the following issue when running snakemake:
```
File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpd0ajxt9a.build_shapes.py", line 21, in _get_country
    return getattr(pyc.countries.get(**keys), target)
AttributeError: 'NoneType' object has no attribute 'alpha_3'
[Thu Feb  7 10:32:17 2019]
Error in rule build_shapes:
    jobid: 14
    output: resources/country_shapes.geojson, resources/offshore_shapes.geojson, resources/europe_shape.geojson, resources/nuts3_shapes.geojson

RuleException:
CalledProcessError in line 81 of /home/pypsa/pypsa-eur/Snakefile:
Command ' set -euo pipefail;  /home/.conda/envs/pypsa-eur/bin/python3.6 /home/pypsa/pypsa-eur/.snakemake/scripts/tmpd0ajxt9a.build_shapes.py ' returned non-zero exit status 1.
  File "/home/pypsa/pypsa-eur/Snakefile", line 81, in __rule_build_shapes
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job build_shapes since they might be corrupted:
resources/country_shapes.geojson
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pypsa/pypsa-eur/.snakemake/log/2019-02-07T102832.252956.snakemake.log
```

I've tried going back to Fiona 1.8.3 instead of 1.8.4, but that doesn't seem to solve the issue.

**Comment by Heronimonimo** [comment]
Thanks for the quick update, I'll try again with the new commit!

**Comment by coroa** [comment]
There is a problem in the current libnetcdf version (1.2.5) which leads to veeery long run-times of the add_electricity rule (see also https://github.com/pydata/xarray/issues/2747). Unfortunately masking that libnetcdf version is not solvable by conda. I added https://github.com/PyPSA/pypsa-eur/blob/master/environment.fixedversions.yaml which is an export of what I am currently running that works.

**Comment by Heronimonimo** [comment]
Will try again with a fresh environment setup based on the fixed yaml.

**Comment by Heronimonimo** [comment]
I think I'm almost there, but now I run into this:
```
INFO:pypsa.io:Imported network base.nc has buses, lines, links, transformers
INFO:__main__:Added connection cost of 584-67363 Eur/MW/a to offwind-ac
INFO:__main__:Added connection cost of 1589-58672 Eur/MW/a to offwind-dc
Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp8o1icwp2.add_electricity.py", line 482, in <module>
    attach_hydro(n, costs, ppl)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp8o1icwp2.add_electricity.py", line 254, in attach_hydro
    inflow.sel(countries=country.loc[ppl.has_inflow].values)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/dataarray.py", line 849, in sel
    **indexers_kwargs)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/dataset.py", line 1610, in sel
    self, indexers=indexers, method=method, tolerance=tolerance)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/coordinates.py", line 355, in remap_label_indexers
    obj, v_indexers, method=method, tolerance=tolerance
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/indexing.py", line 258, in remap_label_indexers
    dim, method, tolerance)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/indexing.py", line 197, in convert_label_indexer
    % index_name)
KeyError: "not all values found in index 'countries'"
[Thu Feb  7 14:50:08 2019]
Error in rule add_electricity:
    jobid: 11
    output: networks/elec.nc

RuleException:
CalledProcessError in line 154 of /home/pypsa/pypsa-eur/Snakefile:
Command ' set -euo pipefail;  /home/.conda/envs/pypsa-eur/bin/python3.6 /home/pypsa/pypsa-eur/.snakemake/scripts/tmp8o1icwp2.add_electricity.py ' returned non-zero exit status 1.
  File "/home/pypsa/pypsa-eur/Snakefile", line 154, in __rule_add_electricity
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pypsa/pypsa-eur/.snakemake/log/2019-02-07T144925.615481.snakemake.log
```
