### ISSUE TITLE
pyproj version incompatible with atlite and vresutils

### ISSUE THREAD

**Issue by Svosw** [PyPSA/pypsa-eur#119]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/environment.yaml). Update via `conda env update -f environment.yaml`.

## Describe the Bug

Running `build_renewable_profiles.py` produces RuntimeError when importing atlite. The version of pyproj used (reverted to 1.9.6 in [979ff3de72ae967967a1189329104ab5ba10b142]) is incompatible with atlite and produces the error message below. The error is not produced with pyproj=2.2.2, the version used before. 

Steps to reproduce the error:
1. Create an environment with pyproj=1.9.6 and atlite
2. Open a python console
3. `import atlite`.

The same error happens at a later stage in build_renewable_profiles at line 286. The cause of the rror is in `vresutils.landuse`, which calls `from vresutils import shapes as vshapes`.
Steps to reproduce the error:
1. Create an environment with pyproj=1.9.6 and vresutils
2. Open a python console
3. `from vresutils import shapes as vshapes`.

## Error Message for atlite
```python
Traceback (most recent call last):
  File "C:\Users\Svosw\Documents\Python\pypsa-eur\.snakemake\scripts\tmpl2ubrvfz.build_renewable_profiles.py", line 164, in <module>
    import atlite
  File "C:\Users\Svosw\miniconda3\envs\pypsa-eur\lib\site-packages\atlite\__init__.py", line 26, in <module>
    from .cutout import Cutout
  File "C:\Users\Svosw\miniconda3\envs\pypsa-eur\lib\site-packages\atlite\cutout.py", line 33, in <module>
    from . import config, datasets
  File "C:\Users\Svosw\miniconda3\envs\pypsa-eur\lib\site-packages\atlite\datasets\__init__.py", line 3, in <module>
    from . import cordex, ncep, era5, sarah
  File "C:\Users\Svosw\miniconda3\envs\pypsa-eur\lib\site-packages\atlite\datasets\cordex.py", line 42, in <module>
    o_lon_p=-162, o_lat_p=39.25))
  File "C:\Users\Svosw\miniconda3\envs\pypsa-eur\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'major axis or radius = 0 or not given'
```

## Error Message for vresutils
```python
Traceback (most recent call last):
  File "C:\Users\Svosw\Documents\Python\pypsa-eur\.snakemake\scripts\tmppnldp1e9.build_renewable_profiles.py", line 286, in <module>
    potentials = config['capacity_per_sqkm'] * vlanduse._cutout_cell_areas(cutout)
  File "C:\Users\Svosw\miniconda3\envs\pypsa-eur\lib\site-packages\vresutils\landuse.py", line 259, in _cutout_cell_areas
    from vresutils import shapes as vshapes
  File "C:\Users\Svosw\miniconda3\envs\pypsa-eur\lib\site-packages\vresutils\shapes.py", line 65, in <module>
    def reproject(geom, fr=pyproj.Proj(proj='longlat'), to=pyproj.Proj(proj='aea', lat_1=33., lat_2=72.)):
  File "C:\Users\Svosw\miniconda3\envs\pypsa-eur\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'major axis or radius = 0 or not given'
```

**Comment by coroa** [comment]
Please file that bug with atlite (if you haven't already). The first aid patch is to remove `cordex` from the import list in `atlite/datasets/__init__.py`.

**Comment by Svosw** [comment]
I have filed the bug with atlite. Do you have a suggestion for a first aid patch regarding the error in vresutils as well?

**Comment by coroa** [comment]
Just remove the reproject function in `shapes.py`. it's not used in `pypsa-eur`.
