### ISSUE TITLE
snakemake not defined in solve_operations_network

### ISSUE THREAD

**Issue by danielelerede-oet** [PyPSA/pypsa-eur#1344]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

After fixing the usage in `solve_operations_network` (see https://github.com/PyPSA/pypsa-eur/pull/1229) I'm currently experiencing a new problem when running it after the latest changes in pypsa-eur. 

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/home/user/pypsa-eur/.snakemake/shadow/tmpu8288gv1/.snakemake/scripts/tmp7qch8gtt.solve_operations_network.py", line 54, in <module>
    n = solve_network(
        ^^^^^^^^^^^^^^
  File "/home/user/pypsa-eur/rules/../scripts/solve_network.py", line 1026, in solve_network
    status, condition = n.optimize(**kwargs)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/pypsa-eur/lib/python3.12/site-packages/pypsa/optimization/optimize.py", line 615, in __call__
    return optimize(self._parent, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/pypsa-eur/lib/python3.12/site-packages/pypsa/optimization/optimize.py", line 587, in optimize
    extra_functionality(n, sns)
  File "/home/user/pypsa-eur/rules/../scripts/solve_network.py", line 986, in extra_functionality
    custom_extra_functionality(n, snapshots, snakemake)
                                             ^^^^^^^^^
NameError: name 'snakemake' is not defined
RuleException:
CalledProcessError in file /home/user/pypsa-eur/rules/solve_electricity.smk, line 76:
Command 'set -euo pipefail;  /home/user/miniforge3/envs/pypsa-eur/bin/python3.12 /home/user/pypsa-eur/.snakemake/shadow/tmpu8288gv1/.snakemake/scripts/tmp7qch8gtt.solve_operations_network.py' returned non-zero exit status 1.
[Wed Oct  2 18:11:57 2024]
Error in rule solve_operations_network:
    jobid: 0
    input: results/networks/base_s_20_elec_lv1_3h.nc
    output: results/networks/base_s_20_elec_lv1_3h_op.nc
    log: results/logs/solve_operations_network/base_s_20_elec_lv1_3h_op_solver.log, results/logs/solve_operations_network/base_s_20_elec_lv1_3h_op_python.log (check log file(s) for error details)
    conda-env: /home/user/pypsa-eur/.snakemake/conda/71bc0087c80dec73ac07303ccfc4cbe5_

Exiting because a job execution failed. Look above for error message
WorkflowError:
At least one job did not complete successfully.
[Wed Oct  2 18:11:57 2024]
Error in rule solve_operations_network:
    jobid: 0
    input: results/networks/base_s_20_elec_lv1_3h.nc
    output: results/networks/base_s_20_elec_lv1_3h_op.nc
    log: results/logs/solve_operations_network/base_s_20_elec_lv1_3h_op_solver.log, results/logs/solve_operations_network/base_s_20_elec_lv1_3h_op_python.log (check log file(s) for error details)
    conda-env: /home/user/pypsa-eur/.snakemake/conda/71bc0087c80dec73ac07303ccfc4cbe5_

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-02T180621.360596.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

**Comment by fneum** [comment]
This error should not really occur unless you have a `custom_extra_functionality`.

You could try:

```yaml
solving:
  options:
    custom_extra_functionality: false
```
