### ISSUE TITLE
Broken scip 9.2.0

### ISSUE THREAD

**Issue by coroa** [PyPSA/pypsa-eur#1409]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

We should maybe add a temporary upper bound to `scip`, due to https://github.com/conda-forge/scipoptsuite-feedstock/issues/80

```
scip <=9.1.1
```
 
## Error Message

```
INFO:linopy.model: Solve problem using Scip solver
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/home/coroa/src/pypsa-eur/.snakemake/scripts/tmp7ko57ga7.cluster_network.py", line 395, in <module>
    n_clusters_c = distribute_n_clusters_to_countries(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coroa/src/pypsa-eur/.snakemake/scripts/tmp7ko57ga7.cluster_network.py", line 232, in distribute_n_clusters_to_countries
    m.solve(solver_name=solver_name)
  File "/home/coroa/.local/conda/envs/pypsa-eur/lib/python3.12/site-packages/linopy/model.py", line 1050, in solve
    assert solver_name in available_solvers, f"Solver {solver_name} not installed"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Solver scip not installed
```

**Comment by fneum** [comment]
fixed already?
