### ISSUE TITLE
Error in a fresh copy when computing availability_matrix for any of the offwind techs

### ISSUE THREAD

**Issue by cristobal-GC** [PyPSA/pypsa-eur#1454]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

On a fresh copy of pypsa-eur, and with *environment.yaml*, I make a copy of *config.default.yaml* into *config_test_01.yaml*. In this new config file  I only change the number of nodes (to consider just 39) and define the folder name *run: name: test_01*. 

Then, the execution of:

> snakemake all --configfile config/config_test_01.yaml

crashes when computing the *availability_matrix_39_offwind-xx* (with xx=ac, dc, float). The error message contains the following:

```
 'data/bundle/gebco/GEBCO_2014_2D.nc' not recognized as being in a supported file format. It could have been recognized by driver HDF5, but plugin gdal_HDF5.so is not available in your installation. You may install it with 'conda install -c conda-forge libgdal-hdf5''*
```

Then, after installing *libgdal-hdf5*, I get a new error at the same stage, including the message:

```
 ValueError: Input shapes do not overlap raster.
```

I repeated the process with *linux-pinned.yaml*, with similar results.

The full text of the error is below.

I can't figure out the reason for the error, since I'm using a fresh copy of the repository with the defined environments.

Any comments are more than welcome, thank you!

## Error Message

```
INFO:__main__:Calculate landuse availability for offwind-float...
ERROR:root:Uncaught exception
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/mask.py", line 80, in raster_geometry_mask
    window = geometry_window(dataset, shapes, pad_x=pad_x, pad_y=pad_y)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/features.py", line 507, in geometry_window
    window = window.intersection(raster_window)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/windows.py", line 785, in intersection
    return intersection([self, other])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/windows.py", line 125, in wrapper
    return function(*args[0])
           ^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/windows.py", line 239, in intersection
    return functools.reduce(_intersection, windows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/windows.py", line 257, in _intersection
    raise WindowError(f"Intersection is empty {w1} {w2}")
rasterio.errors.WindowError: Intersection is empty Window(col_off=-15, row_off=53, width=10, height=8) Window(col_off=0, row_off=0, width=7920, height=4920)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 666, in _process_func
    return shape_availability_reprojected(shapes.loc[[i]], *args)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 361, in shape_availability_reprojected
    masked, transform = shape_availability(geometry, excluder)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 302, in shape_availability
    masked, transform = projected_mask(
                        ^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 216, in projected_mask
    masked, transform_ = mask(raster, geom, crop=True, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/mask.py", line 180, in mask
    shape_mask, transform, window = raster_geometry_mask(
                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/mask.py", line 86, in raster_geometry_mask
    raise ValueError('Input shapes do not overlap raster.')
ValueError: Input shapes do not overlap raster.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cristobal/Desktop/BUZON/aerolinux2/pypsa-eur-test/.snakemake/scripts/tmptvggwx7o.determine_availability_matrix.py", line 182, in <module>
    availability = cutout.availabilitymatrix(regions, excluder, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 747, in compute_availabilitymatrix
    availability = list(pool.map(_process_func, shapes.index))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
    ^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
      ^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 666, in _process_func
    return shape_availability_reprojected(shapes.loc[[i]], *args)[0]
    ^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 361, in shape_availability_reprojected
    masked, transform = shape_availability(geometry, excluder)
      ^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 302, in shape_availability
    masked, transform = projected_mask(
    ^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/atlite/gis.py", line 216, in projected_mask
    masked, transform_ = mask(raster, geom, crop=True, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/mask.py", line 180, in mask
    shape_mask, transform, window = raster_geometry_mask(
      ^^^^^^^^^^^^^^^^^
  File "/home/cristobal/mambaforge-pypy3/envs/pypsa-eur-test_linux-pinned/lib/python3.12/site-packages/rasterio/mask.py", line 86, in raster_geometry_mask
    raise ValueError('Input shapes do not overlap raster.')
    ^^^^^^^^^^^^^^^^^
ValueError: Input shapes do not overlap raster.

```

**Comment by AlexanderMeisinger** [comment]
For me, downgrading the package rasterio to 1.4.1 solved the problem :)

**Comment by cristobal-GC** [comment]
Hi guys, thanks for your feedback,

I just tried what @AlexanderMeisinger proposed, and that worked also for me!
