### ISSUE TITLE
Investigate CI failure on windows

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#161]
Investigate CI failure on windows encountered in #160.

```
Done. Your build exited with 1.

Traceback (most recent call last):

  File "C:\miniconda\envs\pypsa-eur\lib\site-packages\snakemake\__init__.py", line 699, in snakemake

    keepincomplete=keep_incomplete,

  File "C:\miniconda\envs\pypsa-eur\lib\site-packages\snakemake\workflow.py", line 632, in execute

    or delete_temp_output,

  File "C:\miniconda\envs\pypsa-eur\lib\site-packages\snakemake\persistence.py", line 72, in __init__

    os.makedirs(d, exist_ok=True)

  File "C:\miniconda\envs\pypsa-eur\lib\os.py", line 223, in makedirs

    mkdir(name, mode)

NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\travis\\build\\PyPSA\\pypsa-eur\\.snakemake\\aux'
```

**Comment by euronion** [comment]
This is a bug recently introduced into `snakemake` and already fixed upstream.
We just need to wait until the `conda` packages are updated.

See: https://github.com/snakemake/snakemake/issues/411

**Comment by fneum** [comment]
Ah, perfect. Thanks!

**Comment by fneum** [comment]
fixed in https://snakemake.readthedocs.io/en/stable/project_info/history.html#id1
