### ISSUE TITLE
Running into an Error with Pandas Version 1.1.0

### ISSUE THREAD

**Issue by florian-engels** [PyPSA/pypsa-eur#174]
## Describe the Bug

After updating to the new Pandas Version 1.1.0 I couldn't build networks anymore.
Luckily reverting Pandas Back to Version 1.0.5 with
 conda install pandas=1.0.5
is an easy workaround.

## Error Message
```
INFO:pypsa.io:Imported network base.nc has buses, lines, links, transformers
INFO:__main__:Adding 128 generators with capacities
carrier
CCGT    18120.910000
coal    28069.379795
Name: p_nom, dtype: float64
WARNING:__main__:Capital costs for conventional generators put to 0 EUR/MW.
INFO:__main__:Added connection cost of 1104-16560 Eur/MW/a to offwind-ac
INFO:__main__:Added connection cost of 6898-19762 Eur/MW/a to offwind-dc
Traceback (most recent call last):
  File "/home/eike/uni/pypsa/newpypeur/.snakemake/scripts/tmpuqa7g1nl.add_electricity.py", line 541, in <module>
    add_nice_carrier_names(n)
  File "/home/eike/uni/pypsa/newpypeur/.snakemake/scripts/tmpuqa7g1nl.add_electricity.py", line 514, in add_nice_carrier_names
    n.carriers['nice_name'] = nice_names[n.carriers.index]
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/pandas/core/series.py", line 908, in __getitem__
    return self._get_with(key)
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/pandas/core/series.py", line 948, in _get_with
    return self.loc[key]
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/pandas/core/indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/pandas/core/indexing.py", line 1099, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/pandas/core/indexing.py", line 1037, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
    "Passing list-likes to .loc or [] with any missing labels "
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['coal'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
[Tue Aug 11 16:09:30 2020]
Error in rule add_electricity:
    jobid: 5
    output: networks/elec.nc
    log: logs/add_electricity.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 217 of /home/eike/uni/pypsa/newpypeur/Snakefile:
Command 'set -euo pipefail;  /home/eike/miniconda3/envs/newpypsaeur/bin/python3.7 /home/eike/uni/pypsa/newpypeur/.snakemake/scripts/tmpuqa7g1nl.add_electricity.py' returned non-zero exit status 1.
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2135, in run_wrapper
  File "/home/eike/uni/pypsa/newpypeur/Snakefile", line 217, in __rule_add_electricity
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/eike/miniconda3/envs/newpypsaeur/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2201, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/eike/uni/pypsa/newpypeur/.snakemake/log/2020-08-11T160926.549190.snakemake.log
```

**Comment by FabianHofmann** [comment]
Hey @florian-engels, thanks for reporting. Probably a way to solve this is to set 

```
 n.carriers['nice_name'] = nice_names.reindex(n.carriers.index)
```
in add_electricity.py, line 514. 

But a nicer way, would be to find the nice_names which are missing and complete them. You want to try out and make a PR for solving this? Otherwise I take care of it

**Comment by florian-engels** [comment]
Hey @FabianHofmann, you're welcome!
It would be nice if you could take care of it. Because of my vacation I won't find time to search for the names, especially because I'm new to Python, it would take me many hours.
