### ISSUE TITLE
Recent change has broken cluster_network when running for one country only

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#18]
One of the more recent changes has broken the cluster_network script. Have been trying to figure out but can't find what goes wrong. Might this have something to do with a specific pandas version that is needed? Or is it a stupid err on my side?
```
INFO:pypsa.io:Imported network elec_s.nc has buses, carriers, generators, lines, links, loads, storage_units
WARNING:__main__:The configured solver `cbc` does not support quadratic objectives. Falling back to `ipopt`.
Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpgo1s6gwl.cluster_network.py", line 240, in <module>
    potential_mode=potential_mode)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpgo1s6gwl.cluster_network.py", line 164, in clustering_for_n_clusters
    generator_strategies={'p_nom_max': p_nom_max_strategy}
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pypsa/networkclustering.py", line 244, in get_clustering_from_busmap
    buses, linemap, linemap_p, linemap_n, lines = get_buses_linemap_and_lines(network, busmap, line_length_factor, bus_strategies)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pypsa/networkclustering.py", line 219, in get_buses_linemap_and_lines
    buses = aggregatebuses(network, busmap, bus_strategies)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pypsa/networkclustering.py", line 155, in aggregatebuses
    .groupby(busmap).agg(strategies) \
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/generic.py", line 6665, in groupby
    observed=observed, **kwargs)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 2152, in groupby
    return klass(obj, by, **kwds)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 599, in __init__
    mutated=self.mutated)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 3315, in _get_grouper
    if not isinstance(gpr, Grouping) else gpr
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 3025, in __init__
    raise ValueError("Grouper for '%s' not 1-dimensional" % t)
ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional
[Tue Feb 19 10:23:58 2019]
Error in rule cluster_network:
    jobid: 2
    output: networks/elec_s_5.nc, resources/regions_onshore_elec_s_5.geojson, resources/regions_offshore_elec_s_5.geojson, resources/clustermaps_elec_s_5.h5

RuleException:
CalledProcessError in line 188 of /home/pypsa/pypsa-eur/Snakefile:
Command ' set -euo pipefail;  /home/.conda/envs/pypsa-eur/bin/python3.6 /home/pypsa/pypsa-eur/.snakemake/scripts/tmpgo1s6gwl.cluster_network.py ' returned non-zero exit status 1.
  File "/home/pypsa/pypsa-eur/Snakefile", line 188, in __rule_cluster_network
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/concurrent/futures/thread.py", line 56, in run
```
Edit: strangely enough it doesn't happen when running for BE+NL but it does happen when running for DE only

**Comment by fneum** [comment]
I had the same issue recently and I think it is unique to the case where only one country is selected.

The problem seems to be in line 133 in `cluster_network.py` in the function `busmap_for_n_clusters` with a MultiIndex.

**Comment by Heronimonimo** [comment]
> I had the same issue recently and I think it is unique to the case where only one country is selected.
> 
> The problem seems to be in line 133 in `cluster_network.py` in the function `busmap_for_n_clusters` with a MultiIndex.

Yes, that seems to be problem.
