### ISSUE TITLE
hydro_profile is missing countries

### ISSUE THREAD

**Issue by coroa** [PyPSA/pypsa-eur#2]
I think I'm almost there, but now I run into this:
```
INFO:pypsa.io:Imported network base.nc has buses, lines, links, transformers
INFO:__main__:Added connection cost of 584-67363 Eur/MW/a to offwind-ac
INFO:__main__:Added connection cost of 1589-58672 Eur/MW/a to offwind-dc
Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp8o1icwp2.add_electricity.py", line 482, in <module>
    attach_hydro(n, costs, ppl)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp8o1icwp2.add_electricity.py", line 254, in attach_hydro
    inflow.sel(countries=country.loc[ppl.has_inflow].values)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/dataarray.py", line 849, in sel
    **indexers_kwargs)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/dataset.py", line 1610, in sel
    self, indexers=indexers, method=method, tolerance=tolerance)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/coordinates.py", line 355, in remap_label_indexers
    obj, v_indexers, method=method, tolerance=tolerance
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/indexing.py", line 258, in remap_label_indexers
    dim, method, tolerance)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/xarray/core/indexing.py", line 197, in convert_label_indexer
    % index_name)
KeyError: "not all values found in index 'countries'"
[Thu Feb  7 14:50:08 2019]
Error in rule add_electricity:
    jobid: 11
    output: networks/elec.nc

RuleException:
CalledProcessError in line 154 of /home/pypsa/pypsa-eur/Snakefile:
Command ' set -euo pipefail;  /home/.conda/envs/pypsa-eur/bin/python3.6 /home/pypsa/pypsa-eur/.snakemake/scripts/tmp8o1icwp2.add_electricity.py ' returned non-zero exit status 1.
  File "/home/pypsa/pypsa-eur/Snakefile", line 154, in __rule_add_electricity
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pypsa/pypsa-eur/.snakemake/log/2019-02-07T144925.615481.snakemake.log
```

_Originally posted by @Heronimonimo in https://github.com/PyPSA/pypsa-eur/issues/1#issuecomment-461427250_

**Comment by Heronimonimo** [comment]
Found the problem, it was due to only using a subset of countries without hydro. I now get to the point it passes the problem to the solver.

Thanks again!
