### ISSUE TITLE
make_summary brakes on 'links'

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#20]
After solving the network for DE + NL a new problem seems to have shown up in the `make_summary` rule:
```
Traceback (most recent call last):
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'links'
```
It seems to be related with 'links' and pandas. Can't directly figure out what is going on or if it is an error on my side.

Edit: seems to be related to German dataset. Make_summary works fine for NL+BE combo.

**Comment by coroa** [comment]
Does the traceback not include any lines in `make_summary.py`?

**Comment by Heronimonimo** [comment]
Here is the whole traceback, it does indeed include lines in make_summary.
```
Traceback (most recent call last):
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'links'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpkq8p4ky_.make_summary.py", line 430, in <module>
    dfs = make_summaries(networks_dict, country=snakemake.wildcards.country)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpkq8p4ky_.make_summary.py", line 392, in make_summaries
    dfs[output] = globals()["calculate_" + output](n, label, dfs[output])
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpkq8p4ky_.make_summary.py", line 88, in calculate_energy
    energy = include_in_summary(energy, [c.list_name], label, c_energies)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpkq8p4ky_.make_summary.py", line 94, in include_in_summary
    summary.loc[idx[tuple(multiindexprefix + [list(item.index)])], label] = item.values
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexing.py", line 188, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexing.py", line 166, in _get_setitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexing.py", line 247, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexing.py", line 1295, in _convert_to_indexer
    return labels.get_locs(obj)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2618, in get_locs
    self.get_loc_level(k, level=i, drop_level=False)[0]),
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2416, in get_loc_level
    indexer = self._get_level_indexer(key, level=level)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2496, in _get_level_indexer
    loc = level_index.get_loc(key)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'links'
[Thu Feb 21 10:34:11 2019]
Error in rule make_summary:
    jobid: 1
    output: results/summaries/elec_s_all_lc1.0_Co2L-3H_all

RuleException:
CalledProcessError in line 287 of /home/pypsa/pypsa-eur/Snakefile:
Command ' set -euo pipefail;  /home/.conda/envs/pypsa-eur/bin/python3.6 /home/pypsa/pypsa-eur/.snakemake/scripts/tmpkq8p4ky_.make_summary.py ' returned non-zero exit status 1.
  File "/home/pypsa/pypsa-eur/Snakefile", line 287, in __rule_make_summary
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pypsa/pypsa-eur/.snakemake/log/2019-02-21T102211.056546.snakemake.log
```

**Comment by coroa** [comment]
i'm unable to trigger that error with latest master. I did try DE+NL with and without adding tyndp links.

If you want to retest, its helpful to limit the modeled time to maybe a month to get solutions quickly. The config I used is attached.
[config.yaml.txt](https://github.com/PyPSA/pypsa-eur/files/2894948/config.yaml.txt).

**Comment by coroa** [comment]
Hi @Heronimonimo,

does this still happen?

I can't reproduce the problem locally, so we might have fixed it inadvertently.

Best

**Comment by Heronimonimo** [comment]
I haven't seen the error again, so I'll close this issue for now.
