### ISSUE TITLE
TypeError: must be real number, not str

### ISSUE THREAD

**Issue by pz-max** [PyPSA/pypsa-eur#266]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
Solve network seems not to work at the moment. You should be able to reproduce the bug by trying to solve the tutorial version.
The bug appears to be related to the recent PyPSA changes in https://github.com/PyPSA/PyPSA/commit/7a66cf91642857cf43fa844bbb3e75236e8b2806

The error happens in the [`_str_array`](https://github.com/PyPSA/PyPSA/blob/101b0ca5ad839b92a444e81ecef6bfcd1606eeb0/pypsa/linopt.py#L403)  function of linopt.py (pypsa). In particular in these lines:

```
_to_float_str = lambda f: '%+f'%f
_v_to_float_str = np.vectorize(lambda f: '%+f'%f, otypes=[object])
```
My guess is that somehow arrays like `array([["5>=3"]])` or `array([[""]])` are passed that lead to the below error message. Any idea how to solve that issue?

## Error Message

INFO:pypsa.io:Imported network elec_s_5_ec_lcopt_Co2L-24H.nc has buses, carriers, generators, global_constraints, lines, links, loads, stores
INFO:pypsa.linopf:Prepare linear problem
Traceback (most recent call last):
  File "/home/pypsa-eur-tutorial/.snakemake/shadow/tmp1le9na88/.snakemake/scripts/tmpxbnbbinb.solve_network.py", line 289, in <module>
    n = solve_network(n, config=snakemake.config, opts=opts,
  File "/home/pypsa-eur-tutorial/.snakemake/shadow/tmp1le9na88/.snakemake/scripts/tmpxbnbbinb.solve_network.py", line 264, in solve_network
    ilopf(n, solver_name=solver_name, solver_options=solver_options,
  File "/home/max/anaconda3/envs/pypsa-eur-new/lib/python3.8/site-packages/pypsa/linopf.py", line 1027, in ilopf
    status, termination_condition = network_lopf(n, snapshots, **kwargs)
  File "/home/max/anaconda3/envs/pypsa-eur-new/lib/python3.8/site-packages/pypsa/linopf.py", line 907, in network_lopf
    fdp, problem_fn = prepare_lopf(n, snapshots, keep_files, skip_objective,
  File "/home/max/anaconda3/envs/pypsa-eur-new/lib/python3.8/site-packages/pypsa/linopf.py", line 617, in prepare_lopf
    define_dispatch_for_non_extendable_variables(n, snapshots, c, attr)
  File "/home/max/anaconda3/envs/pypsa-eur-new/lib/python3.8/site-packages/pypsa/linopf.py", line 115, in define_dispatch_for_non_extendable_variables
    define_constraints(n, dispatch, '>=', lower, c, 'mu_lower', spec='non_ext')
  File "/home/max/anaconda3/envs/pypsa-eur-new/lib/python3.8/site-packages/pypsa/linopt.py", line 176, in define_constraints
    con = write_constraint(n, lhs, sense, rhs, axes)
  File "/home/max/anaconda3/envs/pypsa-eur-new/lib/python3.8/site-packages/pypsa/linopt.py", line 223, in write_constraint
    lhs, sense, rhs = _str_array(lhs), _str_array(sense), _str_array(rhs)
  File "/home/max/anaconda3/envs/pypsa-eur-new/lib/python3.8/site-packages/pypsa/linopt.py", line 383, in _str_array
    return _v_to_float_str(np.asarray(array))
  File "/home/max/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2163, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/max/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2246, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/home/max/anaconda3/envs/pypsa-eur-new/lib/python3.8/site-packages/pypsa/linopt.py", line 367, in <lambda>
    _to_float_str = lambda f: '%+f'%f
**TypeError: must be real number, not str**

Environment pdf:
[environment_pypsa_eur.pdf](https://github.com/PyPSA/pypsa-eur/files/6938537/environment_pypsa_eur.pdf)

**Comment by fneum** [comment]
If you use the latest release of PyPSA (0.17.1) it should work. The PyPSA master branch is not yet compatible with PyPSA-Eur (e.g. #259 is required first). We have that on the list for the upcoming 1-2 weeks.

**Comment by fneum** [comment]
#259 is in now and seems to work also for the PyPSA master branch. Could you try that (remove the networks folder beforehand)? Was unable to reproduce this error.

**Comment by martacki** [comment]
according to the attached pdf, @pz-max was using the latest pypsa 0.17.1. For me it worked before updating #259 and works now as well, so cannot reproduce the error, too. Apart from an outdated network, the config.yaml could also be broken. If it exists your local repo, snakemake won't re-create it - my personal re-occurring "Fettnäpfchen" ;)

**Comment by pz-max** [comment]
Hi guys, thank you so much for the feedback!
I couldn't remove that bug so I just reinstalled anaconda.
I guess it was a problem with the environments.
The reinstallation did its job! Happily using the new pypsa version :+1:
