### ISSUE TITLE
AttributeError: 'str' object has no attribute 'to_csv' when solving PyPSA-EUR with HiGHS

### ISSUE THREAD

**Issue by thomgeo** [PyPSA/pypsa-eur#366]
Hi everybody,

I am trying to solve a network with 100 nodes at 3-hourly resolution, and somehow I always get the error message below. It seems like it wants to write the solve status to a logfile, but this status is only a string and can therefore not be converted to csv. 

Do you have an idea what could be the issue?

Best,
Georg

```Traceback (most recent call last):
  File "/home/thomgeo/pypsa-eur/.snakemake/shadow/tmp7vdwgj5f/.snakemake/scripts/tmp7qx0l9aq.solve_network.py", line 295, in <module>
    n = solve_network(n, snakemake.config, opts, solver_dir=tmpdir,
  File "/home/thomgeo/pypsa-eur/.snakemake/shadow/tmp7vdwgj5f/.snakemake/scripts/tmp7qx0l9aq.solve_network.py", line 267, in solve_network
    network_lopf(n, solver_name=solver_name, solver_options=solver_options,
  File "/home/thomgeo/.conda/envs/pypsa-eur/lib/python3.10/site-packages/pypsa/linopf.py", line 1470, in network_lopf
    res = solve(
  File "/home/thomgeo/.conda/envs/pypsa-eur/lib/python3.10/site-packages/pypsa/linopt.py", line 781, in run_and_read_highs
    log.to_csv(solver_logfile, sep="\t")
AttributeError: 'str' object has no attribute 'to_csv'
Not cleaning up /home/thomgeo/pypsa-eur/.snakemake/shadow/tmp7vdwgj5f/.snakemake/scripts/tmp7qx0l9aq.solve_network.py
[Fri May 13 09:08:35 2022]
Error in rule solve_network:
    jobid: 0
    output: results/networks/elec_s_100_ec_lc1_3H.nc
    log: logs/solve_network/elec_s_100_ec_lc1_3H_solver.log, logs/solve_network/elec_s_100_ec_lc1_3H_python.log, logs/solve_network/elec_s_100_ec_lc1_3H_memory.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 333 of /home/thomgeo/pypsa-eur/Snakefile:
Command 'set -euo pipefail;  /home/thomgeo/.conda/envs/pypsa-eur/bin/python3.1 /home/thomgeo/pypsa-eur/.snakemake/shadow/tmp7vdwgj5f/.snakemake/scripts/tmp7qx0l9aq.solve_network.py' returned non-zero exit status 1.
  File "/home/thomgeo/pypsa-eur/Snakefile", line 333, in __rule_solve_network
  File "/home/thomgeo/.conda/envs/pypsa-eur/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-05-13T090743.192682.snakemake.log
```

**Comment by thomgeo** [comment]
I figured it out, it was actually a problem with the solver options, not with the log. It seems like I passed the keyword in an incorrect way and this triggered the error.
