### ISSUE TITLE
Run breaks when DE is not included in country list

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#5]
When only running the model for NL, BE, LU the model breaks. Adding DE solves it but increases the computational load significantly. Problems seems to be related to the base_network.py script:
 ```
File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
[Tue Feb 12 11:19:21 2019]
Error in rule base_network:
    jobid: 6
    output: networks/base.nc

RuleException:
CalledProcessError in line 62 of /home/pypsa/pypsa-eur/Snakefile:
Command ' set -euo pipefail;  /home/.conda/envs/pypsa-eur/bin/python3.6 /home/pypsa/pypsa-eur/.snakemake/scripts/tmp8xt_y9hd.base_network.py ' returned non-zero exit status 1.
  File "/home/pypsa/pypsa-eur/Snakefile", line 62, in __rule_base_network
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/concurrent/futures/thread.py", line 56, in run
```

**Comment by coroa** [comment]
Please include the full stack trace when reporting problems! From the output above I can't judge where in `base_network` the problem lies.

**Comment by Heronimonimo** [comment]
Shure, this is the full trace:
```
INFO:__main__:Removing buses with voltages Float64Index([132.0, 500.0, 750.0], dtype='float64')
INFO:__main__:TYNDP links outside of the covered area (skipping): Biscay Gulf, Italy-France, IFA2, Italy-Montenegro, NordLink, COBRA cable, Thames Estuary Cluster (NEMO-Link), Anglo-Scottish -1, ALEGrO, North Sea Link, HVDC SuedOstLink, HVDC Line A-North, France-Alderney-Britain, Viking DKW-GB, ElecLink, Greenconnector, Hansa PowerBridge I, NorthConnect, HVDC SuedLink, AQUIND Interconnector, HVDC Ultranet, Gridlink, SACOI 3 -1, SACOI 3 -2, NeuConnect
Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp8xt_y9hd.base_network.py", line 499, in <module>
    n = base_network()
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp8xt_y9hd.base_network.py", line 438, in base_network
    buses, links = _add_links_from_tyndp(buses, links)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp8xt_y9hd.base_network.py", line 138, in _add_links_from_tyndp
    links_tyndp["j"] = _find_closest_links(links, links_tyndp, distance_upper_bound=0.8)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp8xt_y9hd.base_network.py", line 35, in _find_closest_links
    new_links[['x2', 'y2', 'x1', 'y1']]
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/scipy/spatial/kdtree.py", line 239, in __init__
    self.maxes = np.amax(self.data,axis=0)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2320, in amax
    out=out, **kwargs)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by Heronimonimo** [comment]
Still going wrong unfortunately:
```
INFO:__main__:Removing buses with voltages Float64Index([132.0, 500.0, 750.0], dtype='float64')
INFO:__main__:TYNDP links outside of the covered area (skipping): Biscay Gulf, Italy-France, IFA2, Italy-Montenegro, NordLink, COBRA cable, Thames Estuary Cluster (NEMO-Link), Anglo-Scottish -1, ALEGrO, North Sea Link, HVDC SuedOstLink, HVDC Line A-North, France-Alderney-Britain, Viking DKW-GB, ElecLink, Greenconnector, Hansa PowerBridge I, NorthConnect, HVDC SuedLink, AQUIND Interconnector, HVDC Ultranet, Gridlink, SACOI 3 -1, SACOI 3 -2, NeuConnect
Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp6uipgpri.base_network.py", line 502, in <module>
    n = base_network()
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp6uipgpri.base_network.py", line 450, in base_network
    links = _set_electrical_parameters_links(links)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp6uipgpri.base_network.py", line 238, in _set_electrical_parameters_links
    links_p_nom["j"] = _find_closest_links(links, links_p_nom)
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmp6uipgpri.base_network.py", line 41, in _find_closest_links
    distance_upper_bound=distance_upper_bound
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/scipy/spatial/kdtree.py", line 485, in query
    raise ValueError("x must consist of vectors of length %d but has shape %s" % (self.m, np.shape(x)))
ValueError: x must consist of vectors of length 4 but has shape (0,)
[Tue Feb 12 16:42:42 2019]
Error in rule base_network:
    jobid: 6
    output: networks/base.nc

RuleException:
CalledProcessError in line 62 of /home/pypsa/pypsa-eur/Snakefile:
Command ' set -euo pipefail;  /home/.conda/envs/pypsa-eur/bin/python3.6 /home/pypsa/pypsa-eur/.snakemake/scripts/tmp6uipgpri.base_network.py ' returned non-zero exit status 1.
  File "/home/pypsa/pypsa-eur/Snakefile", line 62, in __rule_base_network
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/concurrent/futures/thread.py", line 56, in run
```

**Comment by Heronimonimo** [comment]
Unfortunately this still seems to be an issue:
- NL only results in error to attach hydro
- BE only results in error to attach offshore DC

**Comment by Heronimonimo** [comment]
For NL only run it can simply be solved by commenting out line 507 in add_electricity:
`attach_hydro(n, costs, ppl)`
