### ISSUE TITLE
Incompatibility of simplify_network with PyPSA v0.26

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#793]
## Checklist

- [ ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
Traceback (most recent call last):
  File "/home/fneum/bwss/playgrounds/pr/pypsa-eur/.snakemake/scripts/tmpal31ydd4.simplify_network.py", line 566, in <module>
    n, stub_map = remove_stubs(
                  ^^^^^^^^^^^^^
  File "/home/fneum/bwss/playgrounds/pr/pypsa-eur/.snakemake/scripts/tmpal31ydd4.simplify_network.py", line 439, in remove_stubs
    _aggregate_and_move_components(
  File "/home/fneum/bwss/playgrounds/pr/pypsa-eur/.snakemake/scripts/tmpal31ydd4.simplify_network.py", line 268, in _aggregate_and_move_components
    replace_components(n, "Generator", generators, generators_pnl)
  File "/home/fneum/bwss/playgrounds/pr/pypsa-eur/.snakemake/scripts/tmpal31ydd4.simplify_network.py", line 250, in replace_components
    import_components_from_dataframe(n, df, c)
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pypsa/io.py", line 912, in import_components_from_dataframe
    dataframe[k] = dataframe[k].astype(static_attrs.at[k, "typ"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 105, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fneum/miniconda3/envs/pypsa-eur-231204/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 150, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
```

**Comment by fneum** [comment]
closed via https://github.com/PyPSA/pypsa-eur/commit/c304738ea5dc7c14f2b8ce30d688d0fa2ff115f9
