### ISSUE TITLE
build_natura_raster error dependency on output from cutouts

### ISSUE THREAD

**Issue by JanFrederickUnnewehr** [PyPSA/pypsa-eur#95]
The rule build_natura_raster generates the following error while trying to generate the natura.tiff file alone:
`snakemake -f resources/natura.tiff`
This happen from my understanding, because in **build_natura_raster.py** the different needed cutout names generated in line 55 `cutout_names = np.unique([res['cutout'] for res in snakemake.config['renewable'].values()])` 

To generate the xXyY coordinates the function `determine_cutout_xXyY(cutout_name):` needs for each cutout name a file in the cutout folder. 

```
def determine_cutout_xXyY(cutout_name):
    cutout = atlite.Cutout(cutout_name, cutout_dir="cutouts")
```

If one of the folders (cutouts) not existing the following error occurs:

```
(pypsa-eur_47) freddy@intgrid-pc-08:~/Dokumente/pypsa-eur$ snakemake -f resources/natura.tiff
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	build_natura_raster
	1

[Sun Nov 10 18:12:01 2019]
rule build_natura_raster:
    input: data/bundle/natura/Natura2000_end2015.shp
    output: resources/natura.tiff
    jobid: 0

Traceback (most recent call last):
  File "/home/freddy/Dokumente/pypsa-eur/.snakemake/scripts/tmphturyz9q.build_natura_raster.py", line 56, in <module>
    xs, Xs, ys, Ys = zip(*(determine_cutout_xXyY(cutout) for cutout in cutout_names))
  File "/home/freddy/Dokumente/pypsa-eur/.snakemake/scripts/tmphturyz9q.build_natura_raster.py", line 56, in <genexpr>
    xs, Xs, ys, Ys = zip(*(determine_cutout_xXyY(cutout) for cutout in cutout_names))
  File "/home/freddy/Dokumente/pypsa-eur/.snakemake/scripts/tmphturyz9q.build_natura_raster.py", line 48, in determine_cutout_xXyY
    cutout = atlite.Cutout(cutout_name, cutout_dir="cutouts")
  File "/home/freddy/anaconda3/envs/pypsa-eur_47/lib/python3.7/site-packages/atlite/cutout.py", line 87, in __init__
    raise TypeError("Arguments `xs`, `ys` and `years` need to be specified")
TypeError: Arguments `xs`, `ys` and `years` need to be specified
[Sun Nov 10 18:12:02 2019]
Error in rule build_natura_raster:
    jobid: 0
    output: resources/natura.tiff

RuleException:
CalledProcessError in line 128 of /home/freddy/Dokumente/pypsa-eur/Snakefile:
Command 'set -euo pipefail;  /home/freddy/anaconda3/envs/pypsa-eur_47/bin/python3.7 /home/freddy/Dokumente/pypsa-eur/.snakemake/scripts/tmphturyz9q.build_natura_raster.py' returned non-zero exit status 1.
  File "/home/freddy/Dokumente/pypsa-eur/Snakefile", line 128, in __rule_build_natura_raster
  File "/home/freddy/anaconda3/envs/pypsa-eur_47/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/freddy/Dokumente/pypsa-eur/.snakemake/log/2019-11-10T181201.022438.snakemake.log

```

From my understanding the problem could be solved by adding a dependency between rule build_natura_rster and build_cutouts or trying to hand the coordinates for the different cutouts to the build_natura_raster. I have tried the following:

```
def determine_cutout_xXyY(cutout_name):
    cutout_params = snakemake.config['atlite']['cutouts'][cutout_name]
    for p in ('xs', 'ys', 'years', 'months'):
        if p in cutout_params:
            cutout_params[p] = slice(*cutout_params[p]
    cutout = atlite.Cutout(cutout_name, cutout_dir="cutouts", **cutout_params)
    x, X, y, Y = cutout.extent
    dx = (X - x) / (cutout.shape[1] - 1)
    dy = (Y - y) / (cutout.shape[0] - 1)
    return [x - dx/2., X + dx/2., y - dy/2., Y + dy/2.]
```

But atlite.Cutout still needs or searches for the generated cutout files.

I think the easier solution is to add an input dependency from the output of build_cutouts. I'm not sure how to generate this input dependence because no wildcard exists, that describes the different cutouts (number of cutouts can be different `snakemake.config['atlite']['cutouts']`).

**Comment by coroa** [comment]
True, the `build_natura_raster` depends on wind and solar cutouts to be generated and this should be reflected in their `input`s. Feel free to prepare a PR!

**Comment by fneum** [comment]
Thanks for the detailed description @JanFrederickUnnewehr! `expand("cutouts/{cutouts}", **config['atlite'])` does the trick.

**Comment by coroa** [comment]
@fneum nifty!
